# Generated by Django 5.2 on 2025-04-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cloths',
            name='season',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cloths',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
