# Generated by Django 5.2 on 2025-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(max_length=32, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('color', models.CharField(max_length=16, null=True)),
                ('used', models.BooleanField(null=True)),
            ],
        ),
    ]
